"""The shipped screening universe for `screener.py`.

Why a shipped list rather than a live index query
-------------------------------------------------
Yahoo has no keyless, stable "give me the constituents of the STOXX 600"
endpoint, and its predefined screeners (`undervalued_large_caps` and
friends) change composition without notice and differ between yfinance
versions. A screen whose *universe* moves under you cannot be compared
week to week, which is most of the value. So the universe is an explicit,
version-controlled list: boring, auditable, and identical on every run.

Composition — 359 names, biased towards what is actually
investable here:

  * **EU/EEA large caps** (CAC 40, DAX, AEX, IBEX, FTSE MIB, the Nordics,
    Vienna, Brussels, Lisbon, Dublin). These are the half of the board a
    French reader can hold inside a PEA.
  * **Switzerland and the UK**, which are not in the EEA but are where a
    lot of European dividend quality actually sits.
  * **US dividend large caps** — the classic quality/income names, for
    comparison.

Deliberately excluded: micro caps (they fail the market-cap gate anyway
and cost a request each), REITs and BDCs (their payout ratios make the
dividend pillar meaningless without a FFO adjustment this screener does
not do), and anything speculative — a beaten-down dividend payer is by
definition not a speculative bet.

Editing
-------
Do NOT edit this file to add or drop a name for your own reasons — use
`screener_universe.json` in the data folder, which survives an update:

    {"symbols": ["XYZ.PA"], "exclude": ["TTE.PA"]}

This list is the floor, that file is the override. Every share you hold
(every priced holding Yahoo calls an equity) is folded in automatically,
so a share you own is always scored whether or not it is listed here.
"""

from __future__ import annotations

# --- France (CAC 40 and near neighbours) ----------------------------------
_FRANCE = """
AI.PA AIR.PA ALO.PA BN.PA BNP.PA CA.PA CAP.PA CS.PA DG.PA DSY.PA EDEN.PA
EL.PA EN.PA ENGI.PA ERF.PA GLE.PA HO.PA KER.PA LR.PA MC.PA ML.PA OR.PA
ORA.PA PUB.PA RI.PA RMS.PA RNO.PA SAF.PA SAN.PA SGO.PA STLAP.PA SU.PA
SW.PA TE.PA TTE.PA URW.PA VIE.PA VIV.PA WLN.PA ACA.PA KOF.PA FR.PA
"""

# --- Germany (DAX / MDAX selects) -----------------------------------------
_GERMANY = """
ADS.DE AIR.DE ALV.DE BAS.DE BAYN.DE BEI.DE BMW.DE BNR.DE CBK.DE CON.DE
DB1.DE DBK.DE DHL.DE DTE.DE EOAN.DE FME.DE FRE.DE HEI.DE HEN3.DE IFX.DE
MBG.DE MRK.DE MTX.DE MUV2.DE PAH3.DE POR.DE QIA.DE RWE.DE SAP.DE SHL.DE
SIE.DE SY1.DE VNA.DE VOW3.DE ZAL.DE EVK.DE LHA.DE TKA.DE FRA.DE
"""

# --- Netherlands / Belgium / Luxembourg -----------------------------------
_BENELUX = """
ABN.AS ADYEN.AS AD.AS AGN.AS AKZA.AS ASML.AS ASM.AS BESI.AS DSFIR.AS
HEIA.AS INGA.AS KPN.AS NN.AS PHIA.AS RAND.AS REN.AS UNA.AS WKL.AS
ABI.BR ARGX.BR COLR.BR KBC.BR PROX.BR SOLB.BR UCB.BR GBLB.BR
"""

# --- Spain / Portugal / Italy ---------------------------------------------
_SOUTH = """
ACS.MC AENA.MC AMS.MC ANA.MC BBVA.MC CABK.MC ELE.MC ENG.MC FER.MC GRF.MC
IBE.MC ITX.MC MAP.MC MTS.MC NTGY.MC REP.MC SAN.MC TEF.MC
EDP.LS GALP.LS JMT.LS
A2A.MI AZM.MI BAMI.MI BMED.MI ENEL.MI ENI.MI G.MI ISP.MI LDO.MI MB.MI
MONC.MI PST.MI PRY.MI RACE.MI SRG.MI STLAM.MI TRN.MI UCG.MI
"""

# --- Nordics / Austria / Ireland ------------------------------------------
_NORDIC = """
ABB.ST ALFA.ST ASSA-B.ST ATCO-A.ST AZN.ST BOL.ST EPI-A.ST ERIC-B.ST
ESSITY-B.ST EVO.ST HM-B.ST INVE-B.ST NDA-SE.ST SAND.ST SCA-B.ST SEB-A.ST
SHB-A.ST SKF-B.ST SWED-A.ST TEL2-B.ST TELIA.ST VOLV-B.ST
CARL-B.CO DANSKE.CO DEMANT.CO DSV.CO MAERSK-B.CO NOVO-B.CO NZYM-B.CO
ORSTED.CO PNDORA.CO TRYG.CO VWS.CO
FORTUM.HE KNEBV.HE NDA-FI.HE NESTE.HE NOKIA.HE ORNBV.HE SAMPO.HE
STERV.HE UPM.HE WRT1V.HE
DNB.OL EQNR.OL MOWI.OL NHY.OL ORK.OL TEL.OL YAR.OL
ANDR.VI EBS.VI OMV.VI VER.VI VOE.VI
CRH.IR KRZ.IR
"""

# --- Switzerland (CTO only — not PEA-eligible) ----------------------------
_SWISS = """
ABBN.SW ADEN.SW ALC.SW BAER.SW CFR.SW GEBN.SW GIVN.SW HOLN.SW KNIN.SW
LOGN.SW LONN.SW NESN.SW NOVN.SW PGHN.SW ROG.SW SCMN.SW SGSN.SW SIKA.SW
SLHN.SW SOON.SW SREN.SW UBSG.SW UHR.SW ZURN.SW
"""

# --- United Kingdom (CTO only) --------------------------------------------
_UK = """
AAL.L AZN.L BA.L BARC.L BATS.L BP.L BT-A.L DGE.L GLEN.L GSK.L HSBA.L
IMB.L LGEN.L LLOY.L NG.L NWG.L PRU.L REL.L RIO.L RR.L SHEL.L SSE.L
STAN.L TSCO.L ULVR.L VOD.L WPP.L SGRO.L PSON.L
"""

# --- United States (dividend-paying large caps) ---------------------------
_US = """
ABBV ADM ADP AFL AMGN AOS APD AVGO AXP BAC BBY BLK BMY C CAT CB CHRW CINF
CL CLX CMCSA CSCO CTAS CVX D DE DOW DUK EMR EOG ETN EXC F FAST FDX GD GILD
GIS GPC HD HON HPQ IBM INTC ITW JNJ JPM K KHC KMB KO KVUE LMT LOW LYB MCD
MDT MMM MO MRK MS MSFT NEE NKE NOC NUE ORCL PEP PFE PG PM PNC PPG PRU
QCOM RTX SBUX SO SPGI STZ SWK SYY T TGT TROW TRV TXN UNP UPS USB V VZ WBA
WEC WHR WMT WSM XOM
"""

_ASIA_ADR = """
TM SONY MUFG SHG HMC
"""


def _split(*blocks) -> list[str]:
    out: list[str] = []
    for b in blocks:
        out.extend(t for t in b.split() if t)
    return out


DEFAULT_UNIVERSE: list[str] = sorted(set(_split(
    _FRANCE, _GERMANY, _BENELUX, _SOUTH, _NORDIC, _SWISS, _UK, _US, _ASIA_ADR,
)))


if __name__ == "__main__":
    print(f"{len(DEFAULT_UNIVERSE)} symbols")
    for i in range(0, len(DEFAULT_UNIVERSE), 10):
        print("  " + " ".join(DEFAULT_UNIVERSE[i:i + 10]))
