"""The shipped ETF universe for `screener_etf.py`.

Why the ETF universe carries DATA and the share universe carries only symbols
-----------------------------------------------------------------------------
`screener_universe.py` is a bare list of tickers because Yahoo publishes
everything the share board needs. For ETFs it does not. The three facts
that actually decide an ETF — its **TER**, whether it **accumulates or
distributes**, and whether it is **PEA-eligible** — are either missing
from Yahoo for European listings, present in an ambiguous unit, or (in
the PEA case) not derivable from any field at all: PEA eligibility is a
French tax rule about the fund's own holdings and wrapper, and a
synthetically replicated MSCI World can be PEA-eligible while a physical
one is not. No amount of API work produces it.

So each entry ships the curated facts alongside the symbol, and Yahoo
supplies only what Yahoo is good at: price history, fund size, category.
Every row records `ter_source` so the page can say which number it used,
and `screener_etf.py` flags a curated TER that disagrees with Yahoo's by
more than a few basis points — that disagreement is usually a share-class
mix-up, and it is worth seeing rather than averaging away.

TERs are the published ongoing charges from each fund's KID at the date
this file was written. They move (downwards, mostly — the European ETF
price war is real), so treat a figure older than a year as indicative and
correct it in the override file rather than here.

Deliberate exclusions
---------------------
* **US-listed ETFs (VOO, SPY, QQQ, VTI …).** Not a data problem, a legal
  one: without a PRIIPs KID an EU retail investor cannot buy them at a
  European broker. A "best ETFs" board that ranked them would be ranking
  things that cannot be bought, which is worse than not ranking at all.
* **London listings.** Yahoo quotes them in pence (GBp) — the same trap
  `prices.py` documents — and every one of them has a Frankfurt or
  Amsterdam line of the same fund without it.
* **Bond and money-market ETFs.** The board ranks on growth; bonds would
  fill the bottom of it permanently and tell you nothing you did not
  already know. A bond sleeve is an asset-allocation decision, not a
  "best ETF" question.
* **Leveraged and inverse products.** `screener_etf.py` gates them out by
  name as a backstop, but they are not listed here either. A 3x daily
  product's multi-year CAGR is an artefact of volatility drag, so it
  would rank on a number that does not mean what the column header says.
* **ETCs (gold, single-crypto).** They are debt securities, not funds,
  and there is no TER in the UCITS sense.

Editing
-------
Do NOT edit this file for your own additions — use
`screener_etf_universe.json` in the data folder:

    {"etfs": [{"symbol": "XYZ.DE", "ter": 0.0015, "dist": "acc",
               "pea": false, "region": "World"}],
     "exclude": ["EXXT.DE"]}

An entry there overrides the shipped one field by field, so supplying a
corrected TER for a shipped symbol needs only `{"symbol": ..., "ter": ...}`.
Every ETF you hold (every priced holding Yahoo calls a fund) is folded
in automatically with no curated fields, so an ETF you own always appears
on the board even if nobody listed it — it will simply say its TER is
unknown until you add one.
"""

from __future__ import annotations

# symbol, short name, TER as a FRACTION (0.0020 = 0.20%), acc/dist,
# PEA-eligible, region bucket.
#
# `ter=None` means "nobody has told us" — the row still appears, gated out
# with a visible "no TER known" reason, which is the nudge to put the real
# figure in the override file. A guessed TER would be worse: the whole
# point of the board is the cost ranking.
_RAW: list[tuple] = [
    # --- Global developed -------------------------------------------------
    ("IWDA.AS", "iShares Core MSCI World",            0.0020, "acc", False, "World"),
    ("EUNL.DE", "iShares Core MSCI World",            0.0020, "acc", False, "World"),
    ("SWDA.MI", "iShares Core MSCI World",            0.0020, "acc", False, "World"),
    ("XDWD.DE", "Xtrackers MSCI World",               0.0019, "acc", False, "World"),
    ("SPPW.DE", "SPDR MSCI World",                    0.0012, "acc", False, "World"),
    ("EWLD.PA", "Amundi MSCI World",                  0.0038, "acc", False, "World"),
    ("WPEA.PA", "iShares MSCI World Swap PEA",        0.0025, "acc", True,  "World"),
    ("IS3S.DE", "iShares Edge MSCI World Value",      0.0030, "acc", False, "Factor"),
    ("IS3Q.DE", "iShares Edge MSCI World Quality",    0.0030, "acc", False, "Factor"),
    ("IS3R.DE", "iShares Edge MSCI World Momentum",   0.0030, "acc", False, "Factor"),
    ("XDEQ.DE", "Xtrackers MSCI World Quality",       0.0025, "acc", False, "Factor"),
    ("XDEM.DE", "Xtrackers MSCI World Momentum",      0.0025, "acc", False, "Factor"),
    ("XDEV.DE", "Xtrackers MSCI World Value",         0.0025, "acc", False, "Factor"),
    ("WSML.AS", "iShares MSCI World Small Cap",       0.0035, "acc", False, "World"),
    ("IUSN.DE", "iShares MSCI World Small Cap",       0.0035, "acc", False, "World"),

    # --- All-world (developed + emerging) ---------------------------------
    ("VWCE.DE", "Vanguard FTSE All-World",            0.0022, "acc", False, "All-World"),
    ("VWRL.AS", "Vanguard FTSE All-World",            0.0022, "dist", False, "All-World"),
    ("IUSQ.DE", "iShares MSCI ACWI",                  0.0020, "acc", False, "All-World"),
    ("SPYY.DE", "SPDR MSCI ACWI",                     0.0012, "acc", False, "All-World"),
    ("SPYI.DE", "SPDR MSCI ACWI IMI",                 0.0017, "acc", False, "All-World"),

    # --- United States ----------------------------------------------------
    ("CSPX.AS", "iShares Core S&P 500",               0.0007, "acc", False, "US"),
    ("SXR8.DE", "iShares Core S&P 500",               0.0007, "acc", False, "US"),
    ("IUSA.AS", "iShares Core S&P 500",               0.0007, "dist", False, "US"),
    ("VUAA.DE", "Vanguard S&P 500",                   0.0007, "acc", False, "US"),
    ("VUSA.AS", "Vanguard S&P 500",                   0.0007, "dist", False, "US"),
    ("SPY5.DE", "SPDR S&P 500",                       0.0003, "dist", False, "US"),
    ("ESE.PA",  "BNP Paribas Easy S&P 500",           0.0012, "acc", True,  "US"),
    ("PE500.PA", "Amundi PEA S&P 500",                None,   "acc", True,  "US"),
    ("CNDX.AS", "iShares Nasdaq 100",                 0.0030, "acc", False, "US"),
    ("SXRV.DE", "iShares Nasdaq 100",                 0.0030, "acc", False, "US"),
    ("EXXT.DE", "iShares Nasdaq-100",                 0.0031, "dist", False, "US"),
    ("XNAS.DE", "Xtrackers Nasdaq 100",               0.0020, "acc", False, "US"),
    ("QDVE.DE", "iShares S&P 500 Information Tech",   0.0015, "acc", False, "Sector"),
    ("ZPRV.DE", "SPDR MSCI USA Small Cap Value",      0.0030, "acc", False, "US"),

    # --- Europe -----------------------------------------------------------
    ("MEUD.PA", "Amundi Stoxx Europe 600",            0.0007, "acc", True,  "Europe"),
    ("EXSA.DE", "iShares STOXX Europe 600",           0.0020, "dist", False, "Europe"),
    ("IMEU.AS", "iShares MSCI Europe",                0.0012, "acc", False, "Europe"),
    ("EXW1.DE", "iShares Core EURO STOXX 50",         0.0009, "dist", False, "Europe"),
    ("EXS1.DE", "iShares Core DAX",                   0.0016, "dist", False, "Europe"),
    ("DBXD.DE", "Xtrackers DAX",                      0.0009, "acc", False, "Europe"),
    ("CAC.PA",  "Amundi CAC 40",                      0.0025, "dist", True,  "Europe"),
    ("ZPRX.DE", "SPDR MSCI Europe Small Cap Value",   0.0030, "acc", False, "Europe"),

    # --- Emerging markets -------------------------------------------------
    ("EIMI.AS", "iShares Core MSCI EM IMI",           0.0018, "acc", False, "EM"),
    ("IS3N.DE", "iShares Core MSCI EM IMI",           0.0018, "acc", False, "EM"),
    ("XMME.DE", "Xtrackers MSCI Emerging Markets",    0.0018, "acc", False, "EM"),
    ("PAEEM.PA", "Amundi PEA MSCI Emerging Markets",  None,   "acc", True,  "EM"),

    # --- Dividend / income ------------------------------------------------
    # The bridge to the income board: these are the collective version of
    # the same question, and the comparison "does the best single dividend
    # payer beat the dividend ETF after its TER" is the one worth asking.
    #
    # Every symbol below was resolved against Yahoo before being listed
    # (2026-09-08), because a plausible-looking ticker is the one error
    # this file cannot survive: `GGRA.DE` is Gartner Inc, not the
    # WisdomTree dividend-growth fund it looks like, and `QDVI.DE` is a
    # USA Value Factor ETF, not a dividend one. A wrong-but-valid symbol
    # does not fail — it silently ranks the wrong security.
    #
    # World / global
    ("VHYL.AS", "Vanguard FTSE All-World High Div",   0.0029, "dist", False, "Dividend"),
    ("VGWD.DE", "Vanguard FTSE All-World High Div",   0.0029, "dist", False, "Dividend"),
    ("TDIV.AS", "VanEck Dev. Markets Div Leaders",    0.0038, "dist", False, "Dividend"),
    ("ISPA.DE", "iShares STOXX Global Select Div 100", 0.0046, "dist", False, "Dividend"),
    ("ZPRG.DE", "SPDR S&P Global Dividend Aristocrats", 0.0045, "dist", False, "Dividend"),
    ("FGEQ.DE", "Fidelity Global Quality Income",     0.0040, "dist", False, "Dividend"),
    ("SGQI.PA", "Amundi Global Equity Quality Income", 0.0045, "dist", False, "Dividend"),

    # United States
    # EXX5 was listed here as "iShares DivDAX" until 2026-09-08. Yahoo
    # resolves it to iShares Dow Jones U.S. Select Dividend (DE) — a
    # different index, a different continent. DivDAX is EXSB.DE, now
    # listed separately below. The TERs coincide at 0.31%, which is
    # exactly why the error survived: nothing about the number looked
    # wrong.
    ("EXX5.DE", "iShares Dow Jones U.S. Select Dividend", 0.0031, "dist", False, "Dividend"),
    ("SPYD.DE", "SPDR S&P US Dividend Aristocrats",   0.0035, "dist", False, "Dividend"),
    ("FUSD.DE", "Fidelity US Quality Income",         0.0025, "dist", False, "Dividend"),
    ("UDVD.DE", "Franklin US Dividend Tilt",          None,   "dist", False, "Dividend"),

    # Europe — the only bucket where PEA eligibility is even possible, and
    # it still has to be curated per share class rather than inferred from
    # the fund holding European shares.
    ("IQQA.DE", "iShares Euro Dividend",              0.0040, "dist", False, "Dividend"),
    ("IDVY.AS", "iShares Euro Dividend",              0.0040, "dist", False, "Dividend"),
    ("SPYW.DE", "SPDR S&P Euro Dividend Aristocrats", 0.0030, "dist", False, "Dividend"),
    ("EXSH.DE", "iShares STOXX Europe Select Div 30", 0.0031, "dist", False, "Dividend"),
    ("DXSA.DE", "Xtrackers Euro Stoxx Quality Dividend", 0.0030, "dist", False, "Dividend"),
    ("XZDE.DE", "Xtrackers MSCI Europe High Div Yield ESG", 0.0025, "dist", False, "Dividend"),
    ("EXSB.DE", "iShares DivDAX",                     0.0031, "dist", False, "Dividend"),
    ("IQQD.DE", "iShares UK Dividend",                0.0040, "dist", False, "Dividend"),

    # Asia and emerging markets
    ("ZPRA.DE", "SPDR S&P Pan Asia Dividend Aristocrats", 0.0055, "dist", False, "Dividend"),
    ("EUNY.DE", "iShares EM Dividend",                0.0065, "dist", False, "Dividend"),
    ("SPYV.DE", "SPDR S&P EM Dividend Aristocrats",   0.0055, "dist", False, "Dividend"),
    ("WTED.DE", "WisdomTree EM SmallCap Dividend",    0.0054, "dist", False, "Dividend"),

    # --- Property / REIT income -------------------------------------------
    # Listed, not excluded, and tagged as its own region so the flag
    # "single sector — a concentrated bet" fires on every one of them.
    # The share board drops REITs because a payout ratio is meaningless
    # without an FFO adjustment; that objection does not transfer, because
    # a fund's yield is the cash it actually distributed and needs no
    # earnings measure to interpret. What remains true is that these are a
    # sector bet, and the flag says so.
    ("IPRP.AS", "iShares European Property Yield",    0.0040, "dist", False, "Property"),
    ("IQQP.DE", "iShares European Property Yield",    0.0040, "dist", False, "Property"),
    ("IWDP.AS", "iShares Developed Markets Property Yield", 0.0059, "dist", False, "Property"),
    ("TRET.AS", "VanEck Global Real Estate",          0.0025, "dist", False, "Property"),

    # --- Themes / sectors -------------------------------------------------
    ("XAIX.DE", "Xtrackers AI & Big Data",            0.0035, "acc", False, "Theme"),
    ("SMH.AS",  "VanEck Semiconductor",               0.0035, "acc", False, "Theme"),
    ("RBOT.AS", "iShares Automation & Robotics",      0.0040, "acc", False, "Theme"),
    ("IQQH.DE", "iShares Global Clean Energy",        0.0065, "dist", False, "Theme"),
]

_FIELDS = ("symbol", "name", "ter", "dist", "pea", "region")

DEFAULT_ETF_UNIVERSE: list[dict] = [dict(zip(_FIELDS, row)) for row in _RAW]


if __name__ == "__main__":
    known = [e for e in DEFAULT_ETF_UNIVERSE if e["ter"] is not None]
    print(f"{len(DEFAULT_ETF_UNIVERSE)} ETFs "
          f"({len(known)} with a curated TER, "
          f"{sum(1 for e in DEFAULT_ETF_UNIVERSE if e['pea'])} PEA-eligible)")
    for e in sorted(DEFAULT_ETF_UNIVERSE, key=lambda x: (x["region"], x["symbol"])):
        ter = "—" if e["ter"] is None else f"{e['ter'] * 100:.2f}%"
        print(f"  {e['symbol']:<10} {ter:>7}  {e['dist']:<4} "
              f"{'PEA' if e['pea'] else '   '}  {e['region']:<10} {e['name']}")
